begin;

-- Preserve the existing table and every original inquiry.
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text, email text, phone text, company text, message text
);
alter table public.contacts
  add column if not exists status text not null default 'pendiente',
  add column if not exists internal_notes text not null default '',
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists revision integer not null default 0;
alter table public.contacts add constraint adler_contacts_status
  check (status in ('pendiente','seguimiento','resuelta'));
alter table public.contacts add constraint adler_contacts_notes_length
  check (char_length(internal_notes) <= 10000);

create table public.adler_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.adler_admins enable row level security;
alter table public.contacts enable row level security;
revoke all on public.adler_admins from public, anon, authenticated;
grant select on public.adler_admins to authenticated;
create policy adler_admin_self on public.adler_admins for select to authenticated
  using (user_id = (select auth.uid()));

-- Old permissive policies would combine with the new ones using OR.
do $$ declare existing record; columns_sql text; sequence_name text;
begin
  for existing in select policyname from pg_policies where schemaname='public' and tablename='contacts'
  loop execute format('drop policy %I on public.contacts', existing.policyname); end loop;
  select string_agg(quote_ident(column_name), ',') into columns_sql
    from information_schema.columns where table_schema='public' and table_name='contacts';
  execute format('revoke select (%1$s), insert (%1$s), update (%1$s), references (%1$s) on public.contacts from public, anon, authenticated', columns_sql);
  sequence_name := pg_get_serial_sequence('public.contacts','id');
  if sequence_name is not null then
    execute format('grant usage on sequence %s to anon, authenticated', sequence_name);
  end if;
end $$;
revoke all on public.contacts from public, anon, authenticated;
grant insert (name,email,phone,company,message) on public.contacts to anon, authenticated;
grant select on public.contacts to authenticated;
grant update (status,internal_notes) on public.contacts to authenticated;
create policy adler_contact_submit on public.contacts for insert to anon, authenticated
  with check (status='pendiente' and internal_notes='' and revision=0);
create policy adler_contact_read on public.contacts for select to authenticated
  using (exists (select 1 from public.adler_admins where user_id=(select auth.uid())));
create policy adler_contact_manage on public.contacts for update to authenticated
  using (exists (select 1 from public.adler_admins where user_id=(select auth.uid())))
  with check (exists (select 1 from public.adler_admins where user_id=(select auth.uid())));

create function public.adler_validate_contact() returns trigger
language plpgsql set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    new.name := btrim(new.name);
    new.email := btrim(new.email);
    new.message := btrim(new.message);
    if new.name is null or char_length(new.name) not between 1 and 120
      or new.email is null or char_length(new.email) not between 3 and 200
      or new.email !~ '^[^[:space:]@<>]+@[^[:space:]@<>]+\.[^[:space:]@<>]+$'
      or new.message is null or char_length(new.message) not between 1 and 5300
      or char_length(coalesce(new.phone,'')) > 40
      or char_length(coalesce(new.company,'')) > 160 then
      raise exception 'La consulta contiene campos no válidos.' using errcode='23514';
    end if;
  else
    new.revision := old.revision + 1;
  end if;
  new.updated_at := now();
  return new;
end $$;
revoke all on function public.adler_validate_contact() from public, anon, authenticated;
create trigger adler_validate_contact before insert or update on public.contacts
  for each row execute function public.adler_validate_contact();
create index if not exists adler_contacts_received on public.contacts(created_at desc, id desc);
create index if not exists adler_contacts_status_received on public.contacts(status, created_at desc, id desc);

-- Invoker permissions and RLS remain active. Parameters are never interpolated.
create function public.adler_search_contacts(p_query text default '', p_status text default '', p_page integer default 0)
returns jsonb language sql stable security invoker set search_path = '' as $$
  with matches as (
    select c.* from public.contacts c
    where (coalesce(p_status,'')='' or c.status=p_status)
      and (coalesce(btrim(p_query),'')='' or position(lower(left(btrim(p_query),200)) in
        lower(concat_ws(' ',c.name,c.email,c.company,c.message))) > 0)
  ), page_rows as (
    select * from matches order by created_at desc,id desc
    limit 50 offset greatest(coalesce(p_page,0),0)::bigint * 50
  )
  select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at desc,p.id desc) from page_rows p),'[]'::jsonb),
    'total',(select count(*) from matches));
$$;
revoke all on function public.adler_search_contacts(text,text,integer) from public, anon, authenticated;
grant execute on function public.adler_search_contacts(text,text,integer) to authenticated;
commit;
